export type StaticComponentVariant = { key: string; name: string; props?: Record<string, unknown> };
export type StaticComponentDefinition = { key: string; name: string; categoryPath: string[]; defaultWidth: number; defaultHeight: number; variants?: StaticComponentVariant[] };
export type StaticSourceDefinition = {
  schemaVersion: string;
  id: string;
  name: string;
  manifestUrl: string;
  runtimeUrl: string;
  protocolVersion: string;
  trustLevel: string;
  module: { name: string; version: string; entry: string; styles: string[] };
  components: readonly StaticComponentDefinition[];
};
export type StaticSourceRegistry = { sources: readonly StaticSourceDefinition[]; sourceById: Map<string, StaticSourceDefinition> };
export type ContractFailure = { ok: false; error: { code: string; message: string } };
export const STATIC_SOURCE_SCHEMA_VERSION: string;
export const OVERLAY_PROTOCOL: string;
export const OVERLAY_PROTOCOL_VERSION: string;
export const OverlayEvent: Readonly<Record<string, string>>;
export const HostCommand: Readonly<Record<string, string>>;
export const ContractErrorCode: Readonly<Record<string, string>>;
export const BUILTIN_STATIC_SOURCES: readonly StaticSourceDefinition[];
export const STATIC_SOURCE_REGISTRY: StaticSourceRegistry;
export function defineStaticSource(source: StaticSourceDefinition): StaticSourceDefinition;
export function createStaticSourceRegistry(sources: readonly StaticSourceDefinition[]): StaticSourceRegistry;
export function resolveStaticComponent(registry: StaticSourceRegistry, selection: { sourceId?: string; componentKey?: string; variantKey?: string; protocolVersion?: string }): ContractFailure | { ok: true; value: { source: StaticSourceDefinition; component: StaticComponentDefinition } };
export function createStaticInstance(registry: StaticSourceRegistry, input: { sourceId?: string; componentKey?: string; variantKey?: string; protocolVersion?: string; instanceId?: string; props?: Record<string, unknown> }): ContractFailure | { ok: true; value: { instanceId: string; sourceId: string; componentKey: string; protocolVersion: string; variantKey?: string; props?: Record<string, unknown> } };
export function staticManifestForSource(source: StaticSourceDefinition): Record<string, unknown>;
export function validateStaticManifest(source: StaticSourceDefinition, manifest: unknown): ContractFailure | { ok: true; value: Record<string, unknown> };
export function createProtocolMessage(sourceId: string, type: string, payload?: Record<string, unknown>): Record<string, unknown>;
export function validateProtocolMessage(value: unknown, options: { sourceId: string; direction: 'host' | 'runtime' }): ContractFailure | { ok: true; value: Record<string, unknown> };
