import { useState } from "react";
import type { ModelAbRunRecord, ModelRecognitionResult } from "../../electron/model-recognition";

export const defaultPrompt = "请识别这张草图可能表示的界面组件。\n请按可能性从高到低列出多个组件类型。\n只描述组件识别，不要搜索组件库，不要生成代码。";

function ResultCard({ title, result }: { title: string; result?: ModelRecognitionResult }) {
  if (!result) return <section className="model-result-card"><h3>{title}</h3><p>尚未运行</p></section>;
  return <section className="model-result-card"><h3>{title}</h3><p>{result.status === "success" ? "完成" : "失败"} · {result.durationMs} ms · Token：{result.tokenUsage.totalTokens ?? "不可用"}</p>{result.components.length ? <ol className="model-component-list">{result.components.map((item) => <li key={item}>{item}</li>)}</ol> : <p className="model-muted">未提取到结构化组件列表</p>}<details><summary>查看原始回答</summary><pre>{result.rawText || result.error}</pre></details></section>;
}

export function ModelAbTestView() {
  const [image, setImage] = useState<string | null>(null); const [imageName, setImageName] = useState(""); const [prompt, setPrompt] = useState(defaultPrompt); const [cli, setCli] = useState<ModelRecognitionResult>(); const [sdk, setSdk] = useState<ModelRecognitionResult>(); const [running, setRunning] = useState<"cli" | "sdk" | "both" | null>(null); const [status, setStatus] = useState("");
  const run = async (mode: "cli" | "sdk" | "both") => { if (!image || !prompt.trim() || running) return; setRunning(mode); setStatus("正在识别…"); const request = (kind: "cli" | "sdk") => window.dockyard?.recognizeModel({ imageDataUrl: image, prompt, mode: kind }); try { if (mode === "both") { const [a, b] = await Promise.all([request("cli"), request("sdk")]); if (a) setCli(a); if (b) setSdk(b); } else { const result = await request(mode); if (result) mode === "cli" ? setCli(result) : setSdk(result); } setStatus("识别完成"); } catch (error) { setStatus(error instanceof Error ? error.message : "识别失败"); } finally { setRunning(null); } };
  const save = async () => { if (!image || (!cli && !sdk)) return; const record: ModelAbRunRecord = { id: `run-${Date.now()}`, createdAt: new Date().toISOString(), prompt, imagePath: imageName || "草图缓存由主进程保存", cli, sdk }; await window.dockyard?.saveModelAbRun(record); setStatus("实验记录已保存"); };
  return <div className="panel-shell model-ab-panel"><header className="window-header"><strong>模型识别对比</strong><button className="window-close" type="button" onClick={() => void window.dockyard?.closePanel("model-ab-test")}>关闭</button></header><main className="model-ab-page"><section className="model-ab-input"><label>草图图片<input type="file" accept="image/png,image/jpeg,image/webp" onChange={(event) => { const file = event.target.files?.[0]; if (!file) return; setImageName(file.name); const reader = new FileReader(); reader.onload = () => setImage(String(reader.result)); reader.readAsDataURL(file); }} /></label>{image && <img className="model-sketch-preview" src={image} alt="当前草图预览" />}<label>提示词<textarea value={prompt} onChange={(event) => setPrompt(event.target.value)} rows={5} /></label><div className="model-ab-actions"><button type="button" disabled={!image || Boolean(running)} onClick={() => void run("both")}>同时运行</button><button type="button" disabled={!image || Boolean(running)} onClick={() => void run("cli")}>运行 CLI</button><button type="button" disabled={!image || Boolean(running)} onClick={() => void run("sdk")}>运行 SDK</button><button type="button" disabled={!image || (!cli && !sdk) || Boolean(running)} onClick={() => void save()}>保存记录</button></div><p className="model-status" role="status">{status}</p></section><section className="model-results"><ResultCard title="Codex CLI" result={cli} /><ResultCard title="Codex SDK" result={sdk} /></section></main></div>;
}
